### ISSUE TITLE
Have problems when installing detectron2 environments

### ISSUE THREAD

**Issue by kinredon** [Vibashan/irg-sfda#1]
Thanks for your great work. 

I am trying to reproduce the results, but get stuck in installing detectron2 environments.

When I follow the [Detectron2 installation](https://detectron2.readthedocs.io/en/latest/tutorials/install.html) , install detectron2 via following command:

```
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```

I have installed detectron2 successfully. But when I train the model, I get the error:

```
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

I found the project has directory `detectron2`, thus we need to install detecron2 by:
```
python -m pip install -e detectron2
```

But I get another error:

```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /mnt/data0/home/codebase/irg-sfda/detectron2
```

Can the author provide some suggestions for me?

Update:

I install detectron2 via:
```
python -m pip install .
```
And then run the train script and raise an error:

![image](https://user-images.githubusercontent.com/39270545/161371608-241d6251-9bac-47ab-aeca-653b857570c8.png)

**Comment by Vibashan** [comment]
Thanks Jinhong Deng.

As per [Detectron2 installation](https://detectron2.readthedocs.io/en/latest/tutorials/install.html) to install detectron, you need to git-clone and perform python -m pip install -e detectron2; here detectron2 is the folder/repo name. 

In irg-sfda case, to install detectron you have to use

```
python -m pip install -e irg-sfda
```

**Comment by kinredon** [comment]
@Vibashan Thanks for your reply. I have installed it successfully, but I get the same error:

![](https://user-images.githubusercontent.com/39270545/161371608-241d6251-9bac-47ab-aeca-653b857570c8.png)

It is raised when the `Corruption_DatasetMapper` is not in the file `.dataset_mapper`. 

I remove it from `data/build.py`, but get: 
```
  File "/mnt/data0/home/dengjinhong/irg-sfda/detectron2/modeling/meta_arch/__init__.py", line 10, in <module>
    from .ttda_rcnn import ttda_RCNN
ModuleNotFoundError: No module named 'detectron2.modeling.meta_arch.ttda_rcnn'
```
Further, this is caused by there being no `ttda_rcnn` in `meta_arch`, I continue to remove it.

Now, no module `test_time_augmentation`:
```
  File "/mnt/data0/home/dengjinhong/irg-sfda/detectron2/modeling/__init__.py", line 48, in <module>
    from .test_time_augmentation import DatasetMapperTTA, GeneralizedRCNNWithTTA
ModuleNotFoundError: No module named 'detectron2.modeling.test_time_augmentation'
```
I remove it again. A new error appears:
```
Traceback (most recent call last):
  File "tools/train_st_sfda_net.py", line 419, in <module>
    launch(
  File "/mnt/data0/home/dengjinhong/irg-sfda/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/train_st_sfda_net.py", line 403, in main
    model_student = build_model(cfg)
  File "/mnt/data0/home/dengjinhong/irg-sfda/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/mnt/data0/home/dengjinhong/irg-sfda/detectron2/config/config.py", line 190, in wrapped
    init_func(self, **explicit_args)
  File "/mnt/data0/home/dengjinhong/irg-sfda/detectron2/modeling/meta_arch/student_sfda_rcnn.py", line 82, in __init__
    self.Graph_conloss = GraphConLoss()
  File "/mnt/data0/home/dengjinhong/irg-sfda/detectron2/modeling/meta_arch/losses.py", line 14, in __init__
    super(GraphConLoss_new_st, self).__init__()
NameError: name 'GraphConLoss_new_st' is not defined
```
I cannot find the class `GraphConLoss_new_st`, I think the author may forget to add it.

**Comment by Vibashan** [comment]
@kinredon Thanks, I fixed these issues. Thanks for noticing it. In initialization can you change super(GraphConLoss_new_st, self).__init__() to super(GraphConLoss, self).__init__(). I missed renaming it.

**Comment by Fly-dream12** [comment]
Since I have installed detectron2 before, i just run the command python setup.py build develop. When I train the model, the import error happens. And the detectron2 is not referred to that in this project, but the detectron2 under my environment. What should I do？ Thanks

**Comment by Fly-dream12** [comment]
Since I have installed detectron2 before, i just run the command python setup.py build develop. When I train the model, the import error happens. And the detectron2 is not referred to that in this project, but the detectron2 under my environment. What should I do？ Thanks @Vibashan @kinredon

**Comment by Vibashan** [comment]
Thanks @Fly-dream12 .

As per [Detectron2 installation](https://detectron2.readthedocs.io/en/latest/tutorials/install.html) to install detectron, you need to git-clone and perform python -m pip install -e detectron2; here detectron2 is the folder/repo name. 

In irg-sfda case, to install detectron you have to use

```
python -m pip install -e irg-sfda
```

So please uninstall your current detectron2 and run the above command.

**Comment by Vibashan** [comment]
If there are any issues, please feel free to open it again.
