### ISSUE TITLE
Why the example evaluation scripts regarding foggy could be runnable when I don't make any foggy_cityscape dataset?

### ISSUE THREAD

**Issue by chenxinli001** [Vibashan/irg-sfda#11]
Why the example evaluation scripts 

CUDA_VISIBLE_DEVICES=$GPU_ID python tools/plain_test_net.py --eval-only \ 
--config-file configs/sfda/foggy_baseline.yaml --model-dir $PATH TO CHECKPOINT

regarding foggy could be runnable when I don't make any foggy_cityscape dataset?

Also, i CANT find the relevant info about adding fog in FoggyDetectionEvaluator. i AM so confused.

**Comment by qnn-a** [comment]
你好 这个问题你解决了吗？
