### ISSUE TITLE
Problems of path change

### ISSUE THREAD

**Issue by huamiao1012** [Vibashan/irg-sfda#2]
Hi! I have some problems when I want to reproduce the results.
When I want to change the path of dataset, I get the error:
`AssertionError: Dataset 'cityscape_2007_train_s' is already registered!`
Can you provide some suggestions for me? Thank you!

**Comment by Vibashan** [comment]
Hi @huamiao1012 ,

Can you please provide a complete error message?.

**Comment by Vibashan** [comment]
As there is no response, I will close the issue. But feel free to open it if you face this issue again.

Thanks
