### ISSUE TITLE
Only single batch is supported during training？

### ISSUE THREAD

**Issue by ygzhu** [Vibashan/irg-sfda#3]
Thanks for your contributions! I find all of the configs with the IMS_PER_BATCH=1, and 
https://github.com/Vibashan/irg-sfda/blob/5a640001cfc38ef3ac416935677a5b15d3918602/detectron2/modeling/roi_heads/roi_heads.py#L486-L488
https://github.com/Vibashan/irg-sfda/blob/5a640001cfc38ef3ac416935677a5b15d3918602/detectron2/modeling/meta_arch/losses.py#L51

The features outputs by ROI_pool and the matrix multiple operation indicate that only single batch is supported during training?

**Comment by Vibashan** [comment]
For domain adaptive object detection people generally use batch size 1. So the current repo and codebase are supported for BS 1.
