### ISSUE TITLE
Error in using detectron 2

### ISSUE THREAD

**Issue by shengyuhao** [Vibashan/irg-sfda#5]
Hi, when I run the comand 'python tools/train_st_sfda_net.py --config-file configs/sfda/sfda_foggy.yaml', it has an error like this:
![image](https://user-images.githubusercontent.com/45036892/204271868-b1cd3862-d001-4c70-87cf-ab74751db835.png)
And I cannot find any "ttda_rcnn" file, could you help me? Thanks a lot.

**Comment by Vibashan** [comment]
Hi,

Thank you for noticing. I have resolved and updated this issues
