### ISSUE TITLE
AP is always 0

### ISSUE THREAD

**Issue by AnnaK-M** [Vibashan/irg-sfda#8]
Hi Mr. Vibashan,

I would like to reproduce your paper but I only get AP values of 0 when I test with your uploaded model with this code:

python tools/plain_test_net.py --eval-only --config-file configs/sfda/foggy_baseline.yaml 
--model-dir model/model_teacher_10.pth

I get the following output:
[08/10 15:36:07 fvcore.common.checkpoint]: [Checkpointer] Loading from model/model_teacher_10.pth ...
WARNING [08/10 15:36:07 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
GraphCN.gc1.{bias, weight}
GraphCN.gc2.{bias, weight}
GraphCN.gc3.{bias, weight}
GraphCN.graph.wk.{bias, weight}
GraphCN.graph.wq.{bias, weight}
Graph_conloss.head_1.0.{bias, weight}
Graph_conloss.head_1.2.{bias, weight}
Graph_conloss.head_2.0.{bias, weight}
Graph_conloss.head_2.2.{bias, weight}
[08/10 15:36:07 detectron2]: Trained model has been sucessfully loaded
...
[08/10 15:37:25 detectron2]: Evaluation results for cityscape_2007_test_t in csv format:
[08/10 15:37:25 d2.evaluation.testing]: copypaste: Task: bbox
[08/10 15:37:25 d2.evaluation.testing]: copypaste: AP,AP50,AP75
[08/10 15:37:25 d2.evaluation.testing]: copypaste: 0.0000,0.0002,0.0000

I also get an AP of 0 after the training with foggy cityscapes with the base source model. I have not altered the code. Do you have any idea what the problem could be? 

Thank you for your work and kind regards,
Anna

**Comment by Vibashan** [comment]
Hi @AnnaK-M ,

Can you try to visualize the results using the pre-trained weights?

**Comment by AnnaK-M** [comment]
Hi @Vibashan,

thanks for the quick response, when I plot the images with predicitons they look something like this:

![result_1](https://github.com/Vibashan/irg-sfda/assets/116202278/202de4ec-c8a5-4716-b774-0ee6865c9843)

It's strange that the predictions have high scores but are really bad. I always get the warning from above, WARNING [08/10 15:36:07 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:, when loading the model. Is that normal?

Do you have any suggestions what the problem might be?

Thanks!

**Comment by Vibashan** [comment]
Hi @AnnaK-M,

It looks like there might be a problem with the dataloader or post-processing script. To debug, you could:

1. Visualize GT using the Val dataloader.
2. If that works, then most probably the issue is with the post-processing script. 

Regarding missing model parameters, it's normal for certain components not to be in the checkpoint. This is expected for as RCNN does not have student network components such as the IRG network.

Let me know if you need more help!

**Comment by AnnaK-M** [comment]
Hi @Vibashan,

Thanks for the comment! I found an error in the post-processing script and took the scaling part out. Now the result looks like this:
![after_processing](https://github.com/Vibashan/irg-sfda/assets/116202278/554ad9d2-6289-4467-8ce1-c57f760c6fe6)
Unfortunately my AP score is still almost 0. 

When looking at this part of the code in the foggy evaluation script:
        # calculate AP score
        if BBGT.size > 0:
                    # compute overlaps
                    # intersection
                    ixmin = np.maximum(BBGT[:, 0], bb[0])
                    iymin = np.maximum(BBGT[:, 1], bb[1])
                    ixmax = np.minimum(BBGT[:, 2], bb[2])
                    iymax = np.minimum(BBGT[:, 3], bb[3])
                    iw = np.maximum(ixmax - ixmin + 1.0, 0.0)
                    ih = np.maximum(iymax - iymin + 1.0, 0.0)
                    inters = iw * ih

            # union
            uni = ((bb[2] - bb[0] + 1.0) * (bb[3] - bb[1] + 1.0)
                + (BBGT[:, 2] - BBGT[:, 0] + 1.0) * (BBGT[:, 3] - BBGT[:, 1] + 1.0)
                - inters )

            overlaps = inters / uni
            ovmax = np.max(overlaps)
            jmax = np.argmax(overlaps)

I notice that iw and ih are almost always 0 and therefore the inters is always 0. I do not understand what the problem is since the predictions in the image without post-processing are quite accurate. Do you have an idea what is wrong in the evaluation?

Thanks for all the help!
Anna

**Comment by AnnaK-M** [comment]
The issue was that width and height were interchanged and therefore the scaling in the post processing was wrong. 

Thanks for the help!

**Comment by chihuy124** [comment]
I am having the same error. Can you be more specific about your solution?
Thanks. @AnnaK-M
